# Para saber mais, acesse https://firebase.google.com/docs/data-connect/reference/graphql

"""
Um tipo de consulta inicial para garantir que o schema seja válido.
"""
type Query {
  hello: String
}

"""
Define uma tabela de Usuários com uma chave primária 'id'.
Esta é uma modelagem inicial para a entidade de usuários.
"""
type Users @table(key: "id") {
  id: ID!
  name: String
  email: String!
}
